node {
    stage('AIT SCM Checkout') {
        git url: 'https://github.com/Ekangaki/maven-web-app-2.git', branch: 'main'
   
   }
    stage('AIT Maven Clean Package') {
        def mavenHome = tool name: "maven-3.9.5", type: "maven"
        def mavenCMD = "${mavenHome}/bin/mvn"
        sh "${mavenCMD} clean package -f maven-web-app-master/pom.xml"
    }
    stage('AIt Build Docker Image') {
        sh 'docker build -t ekangaki/01-maven-web-app maven-web-app-master'
    }
    stage('Push Docker Image') {
        withCredentials([string(credentialsId: 'DOCKER_HUB_PASSWORD', variable: 'DOCKER_HUB_PASSWORD')]) {
            sh "docker login -u ekangaki -p ${DOCKER_HUB_PASSWORD}"
        }
        sh 'docker push ekangaki/01-maven-web-app'
    }
    stage('Run Docker Image In Production Server') {
        def dockerRun = 'docker run -d -p 8080:8080 --name ait-java-web-app ekangaki/01-maven-web-app'

        sshagent(['Docker-Server-SSH']) {
            sh 'ssh -o StrictHostKeyChecking=no ubuntu@172.31.51.57 docker stop ait-java-web-app || true'
            sh 'ssh ubuntu@172.31.51.57 docker rm ait-java-web-app || true'
            sh 'ssh ubuntu@172.31.51.57 docker rmi -f $(docker images -q) || true'
            sh "ssh ubuntu@172.31.51.57 ${dockerRun}"
        }
    }
 
}
